/// <reference path="tabletforeverything.client.d.ts" />

// Code ABOVE is generated by elma365pm. DO NOT EDIT, all changes will be lost.

//Client scripts module

declare const console:any;
//@ts-ignore
console.clear();
declare const document:any;

async function onInit (): Promise<void>
{
}

async function RequestTableForEverything (): Promise<void>
{
    const response = await fetch(Context.data.url+'',{
            method:'POST',
            headers:{ Authorization:`Bearer ${Context.data.authorization}` },
            body:`{
                    "active":true,
                    "size":100,
                    "from":0,
                    "filter":${decodeURIComponent(Context.data.filter+'')},
                    "fields":${decodeURIComponent(Context.data.fields+'')},
                    "sortExpressions":[
                        {
                            "field":"__createdAt",
                            "ascending":true
                        }
                    ]
                }`
        });
    Context.data.json = await response.json();
    if (Context.data.json.success == false)
        throw new Error(Context.data.json.error);
console.log(Context.data.json);
}

async function RenderTableForEverything (): Promise<void>
{
    if (Context.data.fields == null)
        return;
    const fields = Context.data.fields.match(/(?<=")[0-z]+(?=": *true)/gm);
    if (fields == null)
        return;
    const table = document.querySelector("#TableForEverything>.table#"+Context.data.id);
          table.innerHTML = "";
    {
        const row = table.appendChild(document.createElement("div"));
              row.className = "stickytop backgroundvertical tablerow";
        for (var j = 0; j < fields.length; j++)
        {
            const cell = row.appendChild(document.createElement("div"));
                  cell.className = (j==0?"stickyleft ":"")+"backgroundhorizontal tablecell bold";
                  cell.textContent = fields[j];
        }
    }
    for (var i = 0; i < Context.data.json.result.result.length; i++)
    {
        const row = table.appendChild(document.createElement("div"));
              row.className = "backgroundvertical tablerow";
        const element = Context.data.json.result.result[i];
        for (j = 0; j < fields.length; j++)
        {
            const cell = row.appendChild(document.createElement("div"));
                  cell.className = (j==0?"stickyleft ":"")+"backgroundhorizontal tablecell";
                  cell.textContent = element[fields[j]];
        }
    }
}